backend:
  name: github
  repo: prazakovaa/cms-template
  branch: main
  auth_scope: repo

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

site_url: "https://cms-git-template.netlify.app"
root_url: "/admin/"
publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nadpis", name: "title", widget: "string" }
      - { label: "Obsah", name: "body", widget: "markdown" }
      - { label: "Obrázek", name: "image", widget: "image", required: false }